package main

import (
	"context"
	"crypto/sha256"
	"encoding/hex"
	"net/http/httptest"
	"os"
	"path/filepath"
	"testing"

	"github.com/mxschmitt/playwright-go"
	"github.com/zajuna-app/core/internal/capture"
	"github.com/zajuna-app/core/internal/storage/sqlite"
	"github.com/zajuna-app/core/internal/zajuna"
)

var visualBaselines = map[string]string{
	// Filled from deterministic screenshots generated by the same bundled
	// Chromium runtime. Update deliberately when the design changes.
	"desktop": "d82232a2f2ea40c35f0e53d98bfa90e597d835ec7262a8220422d90e5c192cc2",
	"tablet":  "6b23656423dfd2eed3d3eb22c6fbdbe575e4c4c2fca0705a39be536cff4f9ab3",
	"mobile":  "ab8af1557653a5c38d247c008559f8205eb4101809278392070f87c9d3648697",
}

func TestDashboardBrowserSmoke(t *testing.T) {
	if os.Getenv("ZAJUNA_RUN_BROWSER_SMOKE") != "1" {
		t.Skip("browser smoke disabled")
	}

	dataDir := t.TempDir()
	store, err := sqlite.Open(dataDir)
	if err != nil {
		t.Fatal(err)
	}
	defer store.Close()
	if err := writeConfig(dataDir, appConfig{SetupComplete: true, ZajunaUsername: "qa-user", CredentialsStored: true}); err != nil {
		t.Fatal(err)
	}
	if _, err := store.UpsertFichas(context.Background(), []zajuna.Ficha{{ExternalID: "qa-ficha", Name: "Ficha de prueba", CourseID: "qa-course"}}); err != nil {
		t.Fatal(err)
	}
	// Keep date labels stable so the pixel baseline only changes when the UI
	// changes, not on every test run.
	if _, err := store.DB().Exec(`UPDATE fichas SET synced_at = ?, updated_at = ?`, "2026-01-01T12:00:00Z", "2026-01-01T12:00:00Z"); err != nil {
		t.Fatal(err)
	}

	server := httptest.NewServer(newRouterWithServices(dataDir, &memoryCredentialStore{}, nil, store, nil))
	defer server.Close()

	runtime := capture.Resolve("")
	pw, err := runtime.Start()
	if err != nil {
		t.Fatal(err)
	}
	defer pw.Stop()
	browser, err := pw.Chromium.Launch(playwright.BrowserTypeLaunchOptions{
		Headless: playwright.Bool(true),
		// Keep screenshot rasterization stable across repeated local runs. The
		// production Chromium path is intentionally unchanged.
		Args: []string{"--disable-gpu", "--disable-lcd-text", "--font-render-hinting=none"},
	})
	if err != nil {
		t.Fatal(err)
	}
	defer browser.Close()
	browserContext, err := browser.NewContext()
	if err != nil {
		t.Fatal(err)
	}
	defer browserContext.Close()
	page, err := browserContext.NewPage()
	if err != nil {
		t.Fatal(err)
	}
	if _, err := page.Goto(server.URL + "/"); err != nil {
		t.Fatal(err)
	}
	if err := page.Locator("#dashboard-main").WaitFor(playwright.LocatorWaitForOptions{State: playwright.WaitForSelectorStateVisible}); err != nil {
		t.Fatalf("dashboard did not become visible: %v", err)
	}

	title, err := page.Title()
	if err != nil || title != "Zajuna App · Operación local" {
		t.Fatalf("unexpected page title %q: %v", title, err)
	}
	pageTitle, err := page.Locator("#dashboard-title").TextContent()
	if err != nil || pageTitle != "Espacio de trabajo de Zajuna App" {
		t.Fatalf("unexpected dashboard title %q: %v", pageTitle, err)
	}
	for _, selector := range []string{"main[aria-labelledby='dashboard-title']", "#workspace", "#overview-jobs", "#ficha-select", ".evidence-gallery", ".reports-card"} {
		count, err := page.Locator(selector).Count()
		if err != nil || count != 1 {
			t.Fatalf("selector %s count = %d, err = %v", selector, count, err)
		}
	}

	output := filepath.Join(t.TempDir(), "dashboard.png")
	if _, err := page.Screenshot(playwright.PageScreenshotOptions{Path: playwright.String(output), FullPage: playwright.Bool(true)}); err != nil {
		t.Fatal(err)
	}
	if _, err := os.Stat(output); err != nil {
		t.Fatal(err)
	}

	for _, viewport := range []struct {
		name   string
		width  int
		height int
	}{
		{name: "desktop", width: 1440, height: 900},
		{name: "tablet", width: 1024, height: 900},
		{name: "mobile", width: 390, height: 844},
	} {
		if err := page.SetViewportSize(viewport.width, viewport.height); err != nil {
			t.Fatalf("set %s viewport: %v", viewport.name, err)
		}
		if _, err := page.Goto(server.URL + "/resumen"); err != nil {
			t.Fatalf("navigate %s viewport: %v", viewport.name, err)
		}
		if _, err := page.AddStyleTag(playwright.PageAddStyleTagOptions{Content: playwright.String(`*,*::before,*::after { animation:none !important; transition:none !important; caret-color:transparent !important; }`)}); err != nil {
			t.Fatalf("freeze motion at %s viewport: %v", viewport.name, err)
		}
		if _, err := page.Evaluate(`async () => {
			await document.fonts.ready;
			await Promise.all([
				document.fonts.load('650 13px Inter'),
				document.fonts.load('700 27px "Plus Jakarta Sans"'),
				document.fonts.load('600 9px "IBM Plex Mono"'),
			]);
			return true;
		}`); err != nil {
			t.Fatalf("wait fonts at %s viewport: %v", viewport.name, err)
		}
		page.WaitForTimeout(500)
		if err := page.Locator("#workspace").WaitFor(playwright.LocatorWaitForOptions{State: playwright.WaitForSelectorStateVisible}); err != nil {
			t.Fatalf("workspace did not become visible at %s viewport: %v", viewport.name, err)
		}
		overflow, err := page.Evaluate(`() => document.documentElement.scrollWidth <= window.innerWidth + 1`)
		if err != nil {
			t.Fatalf("measure %s viewport: %v", viewport.name, err)
		}
		if visible, ok := overflow.(bool); !ok || !visible {
			t.Fatalf("%s viewport has unexpected horizontal overflow: %#v", viewport.name, overflow)
		}
		unnamed, err := page.Evaluate(`() => Array.from(document.querySelectorAll('button,a,input,select,textarea')).filter((element) => {
			if (element.getAttribute('aria-hidden') === 'true' || element.disabled) return false
			const label = element.getAttribute('aria-label') || element.getAttribute('title') || element.textContent?.trim()
			if (label) return false
			if (element.id && document.querySelector('label[for="' + CSS.escape(element.id) + '"]')) return false
			return !element.closest('label')
		}).map((element) => ({tag: element.tagName, id: element.id, text: element.textContent?.trim()}))`)
		if err != nil {
			t.Fatalf("inspect accessible names at %s viewport: %v", viewport.name, err)
		}
		if values, ok := unnamed.([]any); !ok || len(values) > 0 {
			t.Fatalf("unnamed interactive elements at %s viewport: %#v", viewport.name, unnamed)
		}
		if viewport.width <= 720 {
			visible, err := page.Locator(".sidebar").IsVisible()
			if err != nil || visible {
				t.Fatalf("sidebar should collapse on mobile: visible=%v err=%v", visible, err)
			}
		}
		selectedFicha, err := page.Locator("#ficha-select").InputValue()
		if err != nil || selectedFicha == "" {
			t.Fatalf("unexpected selected ficha at %s viewport: %q (err=%v)", viewport.name, selectedFicha, err)
		}
		responsiveOutput := filepath.Join(t.TempDir(), viewport.name+".png")
		if artifactDir := os.Getenv("ZAJUNA_VISUAL_ARTIFACT_DIR"); artifactDir != "" {
			if err := os.MkdirAll(artifactDir, 0o700); err != nil {
				t.Fatalf("create visual artifact directory: %v", err)
			}
			responsiveOutput = filepath.Join(artifactDir, viewport.name+".png")
		}
		if _, err := page.Screenshot(playwright.PageScreenshotOptions{
			Path:     playwright.String(responsiveOutput),
			FullPage: playwright.Bool(true),
			// Native select text is rasterized by the host widget and can differ
			// by a few pixels between identical Chromium runs. Keep the control
			// geometry in the visual baseline while asserting its value below.
			Style: playwright.String(`.ficha-control { color: transparent !important; }`),
		}); err != nil {
			t.Fatalf("capture %s viewport: %v", viewport.name, err)
		}
		if _, err := os.Stat(responsiveOutput); err != nil {
			t.Fatalf("missing %s visual artifact: %v", viewport.name, err)
		}
		contents, err := os.ReadFile(responsiveOutput)
		if err != nil {
			t.Fatalf("read %s visual artifact: %v", viewport.name, err)
		}
		hash := sha256.Sum256(contents)
		actualHash := hex.EncodeToString(hash[:])
		t.Logf("visual baseline %s sha256=%s", viewport.name, actualHash)
		if expected := visualBaselines[viewport.name]; expected != "" && actualHash != expected {
			t.Fatalf("visual baseline mismatch for %s: got %s want %s", viewport.name, actualHash, expected)
		}
	}
}
